name: Deploy para páginas do GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Verifica o repositório
      - name: Checar o repositório
        uses: actions/checkout@v3

      # 2. Configurar GitHub Pages
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      # 3. Construir o projeto (se necessário)
      - name: Construir os arquivos para deploy
        run: |
          # Exemplo para projetos Node.js:
          # Instala as dependências e gera os arquivos estáticos
          npm install
          npm run build
          
          # Exemplo para projetos Jekyll:
          # Se o seu projeto for baseado no Jekyll, use:
          # bundle install
          # bundle exec jekyll build
          
          # Caso o projeto não precise de construção, você pode omitir este passo.

      # 4. Publicar no GitHub Pages
      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          # Defina o caminho para os arquivos estáticos gerados
          # Caso você tenha uma pasta chamada 'build' ou 'dist', adicione o caminho aqui:
          folder: ./build   # Altere para 'dist', 'public' ou a pasta que seu projeto gera os arquivo
