name: Deploy para páginas do GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checa o repositório
        uses: actions/checkout@v3

      - name: Configura GitHub Pages
        uses: actions/configure-pages@v3

      - name: Cria os arquivos para Deploy
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build  # Substitua "build" pelo diretório correto onde os arquivos do seu site estão

      - name: Publica no GitHub Pages
        uses: actions/deploy-pages@v1
